---
pki_dir: '{{ playbook_dir }}/.pki-dir'
pki_names:
  - C: US
    L: Englewood
    O: Drewfus
    OU: Head Quarters
    ST: New Jersey

pki_key:
  algo: rsa
  size: 4096

pki_self_sign: true
pki_ca:
  expiry: '8760h'
  pathlen: 0
  cname: ca
  sans:
    - ca.vagrant.test

vm_count: 3
vm_domain: vagrant.test
vm_cidr: '192.168.99.0/24'

pki_servers: |-
  [
  {% for i in range(1,vm_count+1) %}
    {
      "cname": "node-{{ i }}.{{ vm_domain }}",
      "profile": "client-server",
      "sans": ["node-{{ i }}.{{ vm_domain }}"],
      "altips": ["{{ vm_cidr | ansible.utils.ipaddr(i+9) }}"]
    }
    {%- if not loop.last -%},{%- endif -%}
  {%- endfor -%}
  ]
