---
version: '3'
tasks:
  delete:
    cmds:
      - vagrant destroy -f
      - rm -rf .pki-dir/ -rf .ansible-roles/ .ansible-factcache/
  python-bootstrap:
    cmds:
      - ansible-playbook python-bootstrap.yml
  ping:
    deps:
      - task: python-bootstrap
    cmds:
      - ansible -m ping vms
  converge:
    deps:
      - task: ping
    cmds:
      - ansible-galaxy install -f -r requirements.yml
      - ansible-playbook playbook.yml
  pki:
    cmds:
      - ansible-galaxy install -f -r pki-requirements.yml
      - ansible-playbook ca.yml
  init:
    cmds:
      - vagrant plugin list
      - vagrant plugin install vagrant-hostmanager
      - vagrant plugin install netaddr
  default:
    cmds:
      - task: pki
      - vagrant up
      - task: converge
